grupo:
    path:     /
    defaults: { _controller: "Grupo3TallerUNLPGrupoBundle:Grupo:index" }

grupo_show:
    path:     /{id}/show
    defaults: { _controller: "Grupo3TallerUNLPGrupoBundle:Grupo:show" }

grupo_new:
    path:     /new
    defaults: { _controller: "Grupo3TallerUNLPGrupoBundle:Grupo:new" }

grupo_create:
    path:     /create
    defaults: { _controller: "Grupo3TallerUNLPGrupoBundle:Grupo:create" }
    requirements: { _method: post }

grupo_edit:
    path:     /{id}/edit
    defaults: { _controller: "Grupo3TallerUNLPGrupoBundle:Grupo:edit" }

grupo_update:
    path:     /{id}/update
    defaults: { _controller: "Grupo3TallerUNLPGrupoBundle:Grupo:update" }
    requirements: { _method: post|put }

grupo_delete:
    path:     /{id}/delete
    defaults: { _controller: "Grupo3TallerUNLPGrupoBundle:Grupo:delete" }
    requirements: { _method: post|delete }
