grupo3_taller_unlp_configuracion:
    resource: "@Grupo3TallerUNLPConfiguracionBundle/Resources/config/routing.yml"
    prefix:   /admin/configuracion

grupo3_taller_unlp_sitio:
    resource: "@Grupo3TallerUNLPSitioBundle/Resources/config/routing.yml"
    prefix:   /admin/sitio

grupo3_taller_unlp_grupo:
    resource: "@Grupo3TallerUNLPGrupoBundle/Resources/config/routing.yml"
    prefix:   /admin/grupo

grupo3_taller_unlp_oficina:
    resource: "@Grupo3TallerUNLPOficinaBundle/Resources/config/routing.yml"
    prefix:   /admin/oficina

grupo3_taller_unlp_host:
    resource: "@Grupo3TallerUNLPHostBundle/Resources/config/routing.yml"
    prefix:   /admin/host

# grupo3_taller_unlp_usuario_red:
#    resource: "@Grupo3TallerUNLPUsuarioRedBundle/Resources/config/routing.yml"
#    prefix:   /admin/usuariored

#grupo3_taller_unlp_menu:
 #   resource: "@Grupo3TallerUNLPMenuBundle/Resources/config/routing.yml"
#    prefix:   /

# grupo3_taller_unlp_user:
#     resource: "@Grupo3TallerUNLPUserBundle/Resources/config/routing.yml"
#     prefix:   /user

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

# fos_user_register:
#     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#     prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# fos_user_group:
#     resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#     prefix: /group

Grupo3TallerUNLPUsuarioRedBundle_usuariored:
  resource: "@Grupo3TallerUNLPUsuarioRedBundle/Resources/config/routing.yml"
  prefix:  /admin/usuariored

  
grupo3_taller_unlp_plantilla:
    resource: "@Grupo3TallerUNLPPlantillaBundle/Resources/config/routing.yml"
    prefix: /plantilla

grupo3_taller_unlp_informepredefinido:
    resource: "@Grupo3TallerUNLPInformePredefinidoBundle/Resources/config/routing.yml"
    prefix: /informepredefinido
